# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 09:51
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('nbsap', '0003_auto_20160506_1053'),
    ]

    operations = []
    for i, lang in enumerate(settings.LANGUAGES):
        if i == 0:
            kw = {'blank': False, 'null': False}
        else:
            kw = {'blank': True, 'null': True}

        operations.append(
            migrations.AddField(
                model_name='aichigoal',
                name='title_%s' % lang[0],
                field=models.TextField(max_length=512, verbose_name=b'Title',
                                       **kw),
            )
        )
        operations.append(
            migrations.AddField(
                model_name='aichigoal',
                name='description_%s' % lang[0],
                field=models.TextField(verbose_name=b'Description', **kw),
            )
        )

        operations.append(
            migrations.AddField(
                model_name='aichitarget',
                name='description_%s' % lang[0],
                field=models.TextField(verbose_name=b'Description', **kw),
            )
        )

        operations.append(
            migrations.AddField(
                model_name='euaction',
                name='title_%s' % lang[0],
                field=models.TextField(max_length=512, verbose_name=b'Title',
                                       **kw),
            )
        )
        operations.append(
            migrations.AddField(
                model_name='euaction',
                name='description_%s' % lang[0],
                field=models.TextField(verbose_name=b'Description', **kw),
            )
        )

        operations.append(
            migrations.AddField(
                model_name='euindicator',
                name='title_%s' % lang[0],
                field=models.TextField(max_length=512, verbose_name=b'Title',
                                       **kw),
            )
        )

        operations.append(
            migrations.AddField(
                model_name='eutarget',
                name='title_%s' % lang[0],
                field=models.TextField(max_length=512, verbose_name=b'Title',
                                       **kw),
            )
        )
        operations.append(
            migrations.AddField(
                model_name='eutarget',
                name='description_%s' % lang[0],
                field=models.TextField(verbose_name=b'Description', **kw),
            )
        )

        operations.append(
            migrations.AddField(
                model_name='nationalaction',
                name='title_%s' % lang[0],
                field=models.TextField(max_length=512, verbose_name=b'Title',
                                       **kw),
            )
        )
        operations.append(
            migrations.AddField(
                model_name='nationalaction',
                name='description_%s' % lang[0],
                field=models.TextField(verbose_name=b'Description', **kw),
            )
        )

        operations.append(
            migrations.AddField(
                model_name='nationalindicator',
                name='title_%s' % lang[0],
                field=models.TextField(max_length=512, verbose_name=b'Title',
                                       **kw),
            )
        )


        operations.append(
            migrations.AddField(
                model_name='nationalobjective',
                name='title_%s' % lang[0],
                field=models.TextField(max_length=512, verbose_name=b'Title',
                                       **kw),
            )
        )
        operations.append(
            migrations.AddField(
                model_name='nationalobjective',
                name='description_%s' % lang[0],
                field=models.TextField(verbose_name=b'Description', **kw),
            )
        )

        operations.append(
            migrations.AddField(
                model_name='nbsappage',
                name='title_%s' % lang[0],
                field=models.TextField(max_length=512, verbose_name=b'Title',
                                       **kw),
            )
        )
        operations.append(
            migrations.AddField(
                model_name='nbsappage',
                name='body_%s' % lang[0],
                field=models.TextField(blank=True, null=True,
                                       verbose_name=b'Description'),
            )
        )


