# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 16:12
from __future__ import unicode_literals
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nbsap', '0006_auto_20160520_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euaichistrategy',
            name='eu_target',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='nbsap.EuTarget',
                verbose_name=b'EU Biodiversity Target'),
        ),
    ]
