# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbsap', '0008_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalindicator',
            name='category',
            field=models.CharField(
                choices=[(b'headline', b'Headline indicators'),
                         (b'other', b'Other indicators')],
                default='headline',
                max_length=32),
            preserve_default=False,
        ),
    ]
