# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('nbsap', '0011_auto_20160614_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='euindicator',
            name='category',
            field=models.CharField(
                choices=[(b'headline', b'Headline indicators'),
                         (b'other', b'Other indicators')],
                default='headline',
                max_length=32),
            preserve_default=False,
        ),
    ]
