# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 15:53
from __future__ import unicode_literals
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('tct', '0002_auto_20160421_0820'),
    ]

    operations = []
    for lang in settings.LANGUAGES:
        operations.append(
            migrations.AddField(
                model_name='nationalindicator',
                name='description_%s' % lang[0],
                field=models.TextField(blank=True, null=True,
                                       verbose_name=b'Description'),
            ),
        )
