# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tct', '0005_auto_20160525_0947'),
        ('tct', '0007_auto_20160520_1112'),
    ]

    operations = [
    ]
