# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbsap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='euaction',
            name='national_strategy',
            field=models.ManyToManyField(blank=True, related_name='eu_actions', to='nbsap.NationalStrategy', verbose_name=b'National strategy'),
        ),
        migrations.AddField(
            model_name='eutarget',
            name='national_strategy',
            field=models.ManyToManyField(blank=True, related_name='eu_targets', to='nbsap.NationalStrategy', verbose_name=b'National objectives'),
        ),
    ]
