# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('nbsap', '0004_auto_20160511_0451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='euaichistrategy',
            options={'verbose_name_plural': ' Mappings: EU targets to Aichi'},
        ),
        migrations.RenameField(
            model_name='euaichistrategy',
            old_name='eu_target',
            new_name='_eu_target',
        ),
        migrations.AddField(
            model_name='euaichistrategy',
            name='eu_targets',
            field=models.ManyToManyField(related_name='eu_aichi_strategy', to='nbsap.EuTarget', verbose_name=b'EU Biodiversity Target'),
        ),
    ]
