# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-16 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('nbsap', '0012_auto_20160615_0542'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='euaction',
        #     name='national_strategy',
        # ),
        # migrations.RemoveField(
        #     model_name='euaichistrategy',
        #     name='eu_target',
        # ),
        # migrations.RemoveField(
        #     model_name='eutarget',
        #     name='national_strategy',
        # ),
        migrations.AlterField(
            model_name='aichigoal',
            name='description_en',
            field=tinymce.models.HTMLField(verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='euaction',
            name='title_en',
            field=models.TextField(verbose_name=b'Title'),
        ),
        migrations.AlterField(
            model_name='nationalaction',
            name='description_en',
            field=tinymce.models.HTMLField(verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='nationalaction',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nbsap.Region'),
        ),
        migrations.AlterField(
            model_name='nationalaction',
            name='title_en',
            field=models.TextField(blank=True, max_length=512, verbose_name=b'Title'),
        ),
        migrations.AlterField(
            model_name='nationalindicator',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='nationalobjective',
            name='description_en',
            field=tinymce.models.HTMLField(verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='nbsappage',
            name='body_en',
            field=models.TextField(blank=True, verbose_name=b'Body'),
        ),
        migrations.AlterField(
            model_name='nbsappage',
            name='title_en',
            field=models.CharField(max_length=128, verbose_name=b'Title'),
        ),
    ]
