# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-20 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('nbsap', '0014_auto_20160929_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSGoal',
            fields=[
                ('code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('title_en', models.TextField(max_length=512, verbose_name=b'Title')),
                ('description_en', tinymce.models.HTMLField(verbose_name=b'Description')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CMSTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('description_en', models.TextField(verbose_name=b'Description')),
                ('aichi_targets', models.ManyToManyField(blank=True, related_name='related_aichi_targets', to='nbsap.AichiTarget')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='euaichistrategy',
            name='eu_target',
        ),
        migrations.AlterField(
            model_name='aichigoal',
            name='description_en',
            field=tinymce.models.HTMLField(verbose_name=b'Description'),
        ),
        migrations.AddField(
            model_name='cmsgoal',
            name='targets',
            field=models.ManyToManyField(related_name='cms_goals', to='nbsap.CMSTarget'),
        ),
    ]
