# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-25 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('nbsap', '0016_auto_20161021_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalaction',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nbsap.Region'),
        ),
        migrations.AlterField(
            model_name='nationalaction',
            name='title_%s' % settings.LANGUAGE_CODE,
            field=models.TextField(blank=True, max_length=512, verbose_name=b'Title'),
        ),
    ]

    for i, lang in enumerate(settings.LANGUAGES):
        if i == 0:
            kw = {}
        else:
            kw = {'blank': True, 'null': True}

        operations.extend([
            migrations.AlterField(
                model_name='aichigoal',
                name='description_%s' % lang[0],
                field=tinymce.models.HTMLField(verbose_name=b'Description', **kw),
            ),
            migrations.AlterField(
                model_name='euaction',
                name='title_%s' % lang[0],
                field=models.TextField(verbose_name=b'Title', **kw),
            ),
            migrations.AlterField(
                model_name='nationalaction',
                name='description_%s' % lang[0],
                field=tinymce.models.HTMLField(verbose_name=b'Description', **kw),
            ),
            migrations.AlterField(
                model_name='nationalobjective',
                name='description_%s' % lang[0],
                field=tinymce.models.HTMLField(verbose_name=b'Description', **kw),
            ),
            migrations.AlterField(
                model_name='nbsappage',
                name='title_%s' % lang[0],
                field=models.CharField(max_length=128, verbose_name=b'Title', **kw),
            ),
        ])

    for i, lang in enumerate(settings.LANGUAGES):
        if i == 0:
            kw = {'default': ''}
            field_kw = {'preserve_default': False}
        else:
            kw = {'blank': True, 'null': True}
            field_kw = {}

        operations.extend([
            migrations.AlterField(
                model_name='nationalindicator',
                name='description_%s' % lang[0],
                field=tinymce.models.HTMLField(verbose_name=b'Description', **kw),
                **field_kw
            ),
            migrations.AlterField(
                model_name='nbsappage',
                name='body_%s' % lang[0],
                field=models.TextField(verbose_name=b'Body', **kw),
                **field_kw
            ),
        ])
